name: "[master] Release"

on:
  push:
    branches:
      - "master"
    paths:
      - "package.json"

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    name: Release Latest on GitHub
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          name: luna-artifacts
          path: ./dist/

      - name: Get version from package.json
        run: |
          VERSION=$(jq -r .version ./dist/package.json)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Publish GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ env.VERSION }}
          prerelease: false
          title: Release ${{ env.VERSION }}
          files: ./dist/luna.zip

      - name: Install Nix
        uses: cachix/install-nix-action@v18

      - name: Run nix-update
        uses: workflow/nix-shell-action@v3
        with:
          packages: nix-update
          script: |
            nix-update --flake --version=${{ env.VERSION }} injection

      - name: Auto-Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5

