name: "[dev] Release"

on:
  push:
    branches:
      - "dev"
    paths:
      - "package.json"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    name: Release Latest on GitHub (Dev)
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          name: luna-artifacts
          path: ./dist/

      - name: Get version from package.json
        run: |
          VERSION=$(jq -r .version ./dist/package.json)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Publish GitHub Release (Dev)
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ env.VERSION }}
          prerelease: true
          title: Dev Release ${{ env.VERSION }}
          files: ./dist/luna.zip

      - name: Install Nix
        uses: cachix/install-nix-action@v18

      - name: Run nix-update
        uses: workflow/nix-shell-action@v3
        with:
          packages: nix-update

